
ENV_KAFKA_BOOTSTRAP_SERVER='KAFKA_BOOTSTRAP_SERVER'
FALLBACK_KAFKA_BOOTSTRAP_SERVER='localhost:9094'
TOPIC_ORDERS_INGEST_PROCESS_MONITOR = 'OrdersIngestProcessMonitor'
TOPIC_ORDER_INGEST_LINES_PROCESSOR = 'OrdersIngestLineProcessor'
TOPIC_FILE_UPLOAD_RECIEVED='OrdersIngestFileUploaded'

DOMAIN = "OrdersIngest"
DOMAIN_CONTEXT = "FileUpload"

EVENTS_KAFKA_BOOTSTRAP_ENV='EVENTS_KAFKA_BOOTSTRAP_SERVER'
EVENTS_KAFKA_TOPIC = "R2Events"

NOTIFICATION_KAFKA_BOOTSTRAP_ENV='NOTIFICATION_KAFKA_BOOTSTRAP_SERVER'
NOTIFICATION_KAFKA_TOPIC = "R2Notification"

METRICS_KAFKA_BOOTSTRAP_ENV='NIGHTHAWK_KAFKA_BOOTSTRAP_SERVER'
METRICS_KAFKA_TOPIC = "R2NightHawk"

ALERT_KAFKA_BOOTSTRAP_ENV='ALERT_KAFKA_BOOTSTRAP_SERVER'
ALERT_KAFKA_TOPIC = "R2Alert"

ELROND_KAFKA_BOOTSTRAP_ENV='EVENTS_KAFKA_BOOTSTRAP_SERVER'
ELROND_KAFKA_TOPIC = "R2OrderIngestProcessMonitor"

DEFAULT_DATE_FORMAT  = "%Y-%m-%d"#"%m-%d-%Y"


